if(NOT CMAKE_HOST_WIN32)
    set(CMAKE_SYSTEM_NAME Windows)
endif()

set(CROSS_TARGET i686-w64-mingw32)
set(ARCH_TRIPLET ${CROSS_TARGET})
set(CMAKE_C_COMPILER ${CROSS_TARGET}-gcc-posix)
set(CMAKE_CXX_COMPILER ${CROSS_TARGET}-g++-posix)
set(CMAKE_RC_COMPILER ${CROSS_TARGET}-windres)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
